config/routes.rb
Rails.application.routes.draw do

  resources :contacts, only: [:new, :create]
  root 'visitors#index'

end

app/models/contact.rb
require 'google_drive_v0'
class Contact
  include ActiveModel::Model
  attr_accessor :name, :string
  attr_accessor :email, :string
  attr_accessor :content, :string

  validates_presence_of :name
  validates_presence_of :email
  validates_presence_of :content
  validates_format_of :email, with: /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i
  validates_length_of :content, :maximum => 500

  def update_spreadsheet
    connection = GoogleDriveV0.login(Rails.application.secrets.email_provider_username, Rails.application.secrets.email_provider_password
)
    ss = connection.spreadsheet_by_title('Mahoney Marriages')
    if ss.nil?
      ss = connection.create_spreadsheet('Mahoney Marriages')
    end
    ws = ss.worksheets[0]
    last_row = 1 + ws.num_rows
    ws[last_row, 1] = Time.new
    ws[last_row, 2] = self.name
    ws[last_row, 3] = self.email
    ws[last_row, 4] = self.content
    ws.save
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(secure_params)
    if @contact.valid?
      @contact.update_spreadsheet
      # TODO send message
      flash[:notice] = "Message sent from #{@contact.name}."
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def secure_params
    params.require(:contact).permit(:name, :email, :content)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/contacts/new.html.erb
<% content_for :title do %>Contact<% end %>
<h3>Contact</h3>
<div class="form">
  <%= simple_form_for @contact do |form| %>
    <%= form.error_notification %>
    <%= form.input :name, autofocus: true %>
    <%= form.input :email %>
    <%= form.input :content, as: :text %>
    <%= form.button :submit, 'Submit', class: 'submit' %>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
        <div class="row">
          <div class="large-4 columns">
            <p>© Mahoney Marriages 2015</p>
          </div>
          <div class="large-4 columns"><%= link_to('Site Created By Preston Copeland', 'http://threemonthcoder.com', :target=>"_blank") %>
          </div>
          <div class="large-4 columns">
            <ul class="inline-list right">
              <li><%= link_to 'About', page_path('about') %></li>
              <li><%= link_to 'Terms of Use', page_path('terms_of_use') %></li>
              <li><%= link_to 'Privacy Policy', page_path('privacy_policy') %></li>
            </ul>
          </div>
        </div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <%= link_to 'x', root_path, {class: 'close'} %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'Home', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>
  <div class="top-bar-section">
    <ul>
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>
<li><%= link_to 'Contact', new_contact_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Mahoney" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Mahoney" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>

    <footer>
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About Bobby and Lisa</h3>
<p>When Bobby is not officiating, he is immersing himself in all things culinary: he provides nutritious meals for students in Harford County, Maryland. His team also caters weddings, so contact him today if you want a wedding that is official--officially delicious!</p>
<p>Lisa is an educational administrator with Baltimore County who brings years of experience teaching English and literature to the table. She will ensure that your ceremony is not only eloquent, but also grammatically flawless. Fun fact: She also studied dance at Towson University, so if you want to learn a few new steps at the reception, she's your resource! </p>

app/views/pages/privacy_policy.html.erb
<% content_for :title do %>Privacy Policy<% end %>
<h3>Privacy Policy</h3>

<p>All rights reserved. And Jude says so, too!</p>

app/views/pages/terms_of_use.html.erb
<% content_for :title do %>Terms of Use<% end %>
<h3>Terms of Use</h3>

<p>No information contained herein may be reproduced or distributed without express permission by the owners or representatives of Mahoney Marriage.</p>

app/views/visitors/index.html.erb
 <section class="hero">
        <div class="row">
          <div class="large-12 columns">
            <div class="main-wrapper">
              <h1 style="color:white">MAHONEY MARRIAGES</h1>
              <h3 style="color:white">Wedding Officiation Services</h3>
              <hr>
              <div class="row">
                <div class="large-6 columns large-centered">
                  <ul class="button-group even-2">
                    <li><%= link_to 'About', page_path('about'), {class: "button"} %></li>
                    <li><%= link_to 'Contact', new_contact_path, {class: "button"} %></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="large-6 columns about-box">
            <div class="black-box">
              <h2 style="color:white">The Mahoneys Are All About Marriage</h2>
              <p>We’re a husband-and-wife pair committed to making your big day as special as ours was!
              <p>Interested in an officiation?</p>
              <%= link_to 'Get in touch →', new_contact_path, {class: "secondary small button"} %>
            </div>
          </div>
        </div>
      </section>

      <section class="hero-content">
      <div class="row">
        <div class="large-8 columns about-content">
          <h4>What We Do</h4>
          <p>We provide officiation services for all sorts of ceremonies. We are licensed with the state of Maryland. We accept everyone with open arms.</p>
          <p>When we're not helping you revel in the most memorable day of your life, we're taking care of our lovely son, Jude, as well as Mr. Peepers, our cat. We love you always, Fiona!</p>
        </div>
        <div class="large-4 columns">
          <ul class="small-block-grid-2">
            <li><a href="#"><img src="http://lorempixel.com/output/cats-q-c-640-480-4.jpg"/></a></li>
            <li><a href="#"><img src="http://lorempixel.com/output/nightlife-q-c-640-480-8.jpg"/></a></li>
            <li><a href="#"><img src="http://lorempixel.com/output/fashion-q-c-640-480-10.jpg"/></a></li>
            <li><a href="#"><img src="http://lorempixel.com/output/people-q-c-640-480-2.jpg"/></a></li>
          </ul>
        </div>
      </div>
      </section>

      <div class="row">
        <div class="large-12 columns">
          <div class="panel">
            <div class="row">
              <div class="large-9 columns">
                <h4>Get in touch!</h4>
                <p>We're available for evening ceremonies during the week, and all day during the weekend.</p>
              </div>
              <div class="large-3 columns">
                <%= link_to 'Contact Us', new_contact_path, {class: "radius button right"} %>
              </div>
            </div>
          </div>
        </div>
      </div>